### ISSUE TITLE
SNAP compatibility

### ISSUE THREAD

**Issue by pbrotoisworo** [insarlab/MiaplPy#19]
I use SNAP to preprocess data for MintPy and I wonder if MiaplPy has the same compatibility.

And a quick question if it is compatible. I was looking at the config and it looks similar to MintPy however there is this option which I'm not familiar with:

```
##---------Coregistered SLC images:        
miaplpy.load.slcFile        = ../merged/SLC/*/*.slc.full  #[path2slc_file]
```

Is that pointing to the wrapped phase imagery?

**Comment by mirzaees** [comment]
Hi @pbrotoisworo! The inputs for MiaplPy  are coregistered SLCs and geometry files (lat, lon, hgt, ..) and the input format is similar to ISCE products (with .vrt and .xml). If you have those, you can use MiaplPy similar to MintPy. We currently don't have support for other formats but we welcome contributions.
Please check the [Jupyter notebook](https://nbviewer.org/github/insarlab/MiaplPy_notebooks/blob/main/miaplpyApp.ipynb) for more instruction on how MiaplPy works
