### ISSUE TITLE
prep_slc_isce.py module load error: isceobj

### ISSUE THREAD

**Issue by jaha2600** [insarlab/MiaplPy#23]
Hi there,
I have recently installed MiaplPy on my local HPC system. Everything seems to install correctly but when I try and run miaplpyApp.py I run into the below error related to module importing during prep_slc_isce.py:

I have MiaPlPy working successfully on a local machine (installed last week) and did not run into this issue, I also have ISCE2 working correctly on the HPC system independently of the MiaPlPy installation. MintPy is also installed on the HPC system and works correctly with the `prep_isce.py` script that they utilize at the start of their workflow.

(miaplpy) [jaha2600@shas0136 miaplpy]$ miaplpyApp.py kigar.txt --dir miaplpy

--RUN-at-2022-09-27 16:34:05.402889--
Current directory: /gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/miaplpy
Run routine processing with arg_parser.py on steps: ['load_data', 'phase_linking', 'concatenate_patches', 'generate_ifgram', 'unwrap_ifgram', 'load_ifgram', 'ifgram_correction', 'invert_network', 'timeseries_correction']
Remaining steps: ['phase_linking', 'concatenate_patches', 'generate_ifgram', 'unwrap_ifgram', 'load_ifgram', 'ifgram_correction', 'invert_network', 'timeseries_correction']
Project name: kigar
--------------------------------------------------
20220927:163405 * miaplpyApp.py kigar.txt --dir miaplpy
Project name: kigar
Go to work directory: /gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/miaplpy/miaplpy
copy default template file /projects/jaha2600/software/miaplpy_programs/MintPy/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/miaplpy/kigar.txt
update default template based on input custom template
    mintpy.compute.cluster: auto --> local
    mintpy.compute.numWorker: auto --> 8
    mintpy.troposphericDelay.method: auto --> no
copy smallbaselineApp.cfg to inputs   directory for backup.
copy smallbaselineApp.cfg to pic      directory for backup.
read default template file: /gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/miaplpy/miaplpy/smallbaselineApp.cfg
update default template based on input custom template
    miaplpy.load.compression: no --> auto
copy miaplpyApp.cfg to inputs   directory for backup.
read default template file: /gpfs/summit/scratch/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/miaplpy/miaplpy/miaplpyApp.cfg
    miaplpy.load.compression: auto --> no
    miaplpy.load.autoPath: yes --> yes
There are 24 workers available, numWorker is changed to 24
SAR platform/sensor : None
processor: isce
check auto path setting for Univ of Miami users for processor: isce
--------------------------------------------------
prepare metadata files for isce products
prep_slc_isce.py -s /scratch/summit/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/merged/SLC -f *.slc.full -m /scratch/summit/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/reference/IW3.xml -b /scratch/summit/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/baselines -g /scratch/summit/jaha2600/GREENLAND/2022/stack_mintpy/kigarsima_slc/merged/geom_reference
Traceback (most recent call last):
  File "/projects/jaha2600/software/miaplpy_programs/MiaplPy/miaplpy/prep_slc_isce.py", line 26, in <module>
    from isceobj.Planet.Planet import Planet
ModuleNotFoundError: No module named 'isceobj'
box to read for datasets in y/x: None
Traceback (most recent call last):
  File "/projects/jaha2600/software/miaplpy_programs/MiaplPy/miaplpy/miaplpyApp.py", line 798, in <module>
    main()
  File "/projects/jaha2600/software/miaplpy_programs/MiaplPy/miaplpy/miaplpyApp.py", line 82, in main
    app.open()
  File "/projects/jaha2600/software/miaplpy_programs/MiaplPy/miaplpy/miaplpyApp.py", line 176, in open
    self.date_list, self.num_pixels, self.metadata = read_initial_info(self.workDir, self.templateFile)
  File "/projects/jaha2600/software/miaplpy_programs/MiaplPy/miaplpy/objects/utils.py", line 1225, in read_initial_info
    num_pixels = (box[2] - box[0]) * (box[3] - box[1])
TypeError: 'NoneType' object is not subscriptable

Have you come across this issue before and have any ideas?
Any help would be fantastic.

**Comment by mirzaees** [comment]
Hi @jaha2600 
Please update to the latest version (I had a few commits today) and try again. Although, your error seems to be related to the isce2 installation. You need to check if isce2 is installed properly.
