### ISSUE TITLE
The platform metadata is missing from load_ifgram.py

### ISSUE THREAD

**Issue by bjmarfito** [insarlab/MiaplPy#3]
- The platform metadata is missing from the load_ifgram.py which causes my timeseries_correction processing step to fail during correct_LOD. 
- A temporary workaround for now is I defined the platform on the miaplpyApp.cfg.

**Comment by mirzaees** [comment]
@bjmarfito This happens when the metadata is not read properly, I think it is better to find the bug for when it is not read and why. Temporarily you could add attributes using 'add_attribute.py' script

**Comment by bjmarfito** [comment]
I see. I further look into this and use your suggestion to use add_attribute.py for now. Thank you @mirzaees!
