### ISSUE TITLE
load_ifgram.py (step 6) fails when running multiple unwrapping networks

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MiaplPy#31]
When I am trying to run `network_single_reference`.  While this is running I started `network_sequential_3` to compare results from two unwrap networks. However, `network_single_reference` throws an error because it wants to use data to be generated by `network_sequential_3`.

The `network_single_reference` run throws this error:

```
prep_isce.py -m /scratch/05861/tg851601/MiamiSenAT48/reference/IW3.xml -g /scratch/05861/tg851601/MiamiSenAT48/merged/geom_reference -b /scratch/05861/tg851601/MiamiSenAT48/baselines  -f /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_sequential_3/*/fi*.unw 
['/scratch/05861/tg851601/MiamiSenAT48/reference/data.rsc'] exists and is newer than ['/scratch/05861/tg851601/MiamiSenAT48/reference/IW3.xml'] --> skip.
preparing RSC file for geometry files
read perp baseline time-series from /scratch/05861/tg851601/MiamiSenAT48/baselines
preparing RSC file for: /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_sequential_3/*/fi*.unw
Traceback (most recent call last):
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/cli/prep_isce.py", line 116, in <module>
    main(sys.argv[1:])
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/cli/prep_isce.py", line 111, in main
    prep_isce(inps)
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/prep_isce.py", line 214, in prep_isce
    prepare_stack(
  File "/work2/05861/tg851601/stampede2/test3_frontera/rsmas_insar/sources/MintPy/mintpy/prep_isce.py", line 137, in prepare_stack
    raise FileNotFoundError(f'NO file found with path pattern: {obs_file}')
FileNotFoundError: NO file found with path pattern: /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_sequential_3/*/fi*.unw
WARNING: mintpy.subset.lalo is not supported if 1) no lookup file AND    2) radar/unkonwn coded dataset
	ignore it and continue.
```

As you see, it looks for `miaplpy/inverted/interferograms_sequential_3/*/fi*.unw` but it has no business to look in an `sequential_3` folder. This is because of the `*` in https://github.com/insarlab/MiaplPy/blob/26da97f26e62b6b5703c1bb2a157687903a8e045/miaplpy/load_ifgram.py#L307

Maybe the `interferograms_sequential_3` directory should be in `network_sequential_3/interferograms`?

**Comment by falkamelung** [comment]
Hi @mirzaees ,  Actually, this could be because I modified $TE/MiamiSenAT48.template before the first run was completed. Or it is related to the location of the `*cfg` file at `/miaplpy/miaplpyApp.cfg` instead of `/miaplpy/network_single_reference/miaplpyApp.cfg` . So I am not sure anymore this is a big problem.

So please think whether this could be a problem and close the issue if it is not.

**Comment by mirzaees** [comment]
Hi @falkamelung, If you are running it for single reference, then why are you using the path to sequential interferograms?
In order to generate the interferograms  for a specific network, it looks at the option in template file. so If you change it in the middle, it will be messed up. you can create the run_files and jobs for each network and then run them separately at the same time.
