### ISSUE TITLE
`NaN or infinity found in input float data` error in unwrapping step

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MiaplPy#32]
I am occasionally getting this error in the unwrapping step. Any idea why this occurs? I have processed this dataset before, possibly with slightly different options (e.g. different starting date). Any idea why this occurs? 
```
cat run_05_miaplpy_unwrap_ifgram_0__10.o
20221029:213429 * unwrap_ifgram.py --ifg /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_single_reference/20210104_20190912/filt_fine.int --coherence /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/tempCoh_average --unwrapped_ifg /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_single_reference/20210104_20190912/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 629 --width 1296 --height 698454.1600760925 --num_tiles 1 --earth_radius 6348066.309525905 --wavelength 0.05546576 -m /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/mask_unwrap --tmp
snaphu -f /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_single_reference/20210104_20190912/config_all -d /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_single_reference/20210104_20190912/filt_fine.int 1296 -o /scratch/05861/tg851601/MiamiSenAT48/miaplpy/inverted/interferograms_single_reference/20210104_20190912/filt_fine.unw
b'NaN or infinity found in input float data\nAbort\n'
Time spent: 0.00882656176884969 m
```
In any case, this error should show up in the `*.e` file.  I will make a note in the `Suggested improvements` issue.

**Comment by falkamelung** [comment]
after re-running ISCE the issue disappears. So there were corrupt files, I suppose. Will add this to the TroubleShooting  section

**Comment by Jesse-kearse** [comment]
I have this same issue: 

20230928:230851 * unwrap_ifgram.py --ifg /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/interferograms_single_reference/20190711_20210218/filt_fine.int --coherence /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/tempCoh_average --unwrapped_ifg /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/interferograms_single_reference/20190711_20210218/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 936 --width 4159 --height 711026.3999666942 --num_tiles 1 --earth_radius 6361925.343755112 --wavelength 0.05546576 -m /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/mask_unwrap
snaphu -f /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/interferograms_single_reference/20190711_20210218/config_all -d /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/interferograms_single_reference/20190711_20210218/filt_fine.int 4159 -o /Volumes/GeoPhysics_28/users-data/kearsejess/insar/work/track_175/miaplpy/inverted/interferograms_single_reference/20190711_20210218/filt_fine.unw
b'NaN or infinity found in input float data\nAbort\n'
Time spent: 0.0017890652020772298 m

@falkamelung which part of ISCE did you re-run? The above error occurred for all ifgs in my single_reference network. I re-ran step 4 to generate the ifgs again, but same issue. I hope I don't need to re-create the SLC stack again..??
