### ISSUE TITLE
How to prepare gamma SLC data for MiapIpy ?

### ISSUE THREAD

**Issue by chenweicug** [insarlab/MiaplPy#49]
I processed some s1 interferograms by gamma and I want us Miapipy to do time series analysis. I found There is no prep_slc_gamma.py scripts. What I need to do in the  prep_slc_gamma.py scripts?

**Comment by mirzaees** [comment]
Hi @chenweicug 
That script is to provide .rsc metadata for input files. Miaplpy mainly supports isce outputs but if you can add prep_slc_gamma.py, it can read gamma outputs as well. I don't have sample data processed with gamma to add/test it. But I appreciate contributions

**Comment by chengbei1** [comment]
thanks
