### ISSUE TITLE
Compatible version of ISCE

### ISSUE THREAD

**Issue by SMJMirza** [insarlab/MiaplPy#50]
Hi,

I tried to run the package with one of the sample datasets but I got the following error at the beginning step:

Traceback (most recent call last):
  File "/home/insar/tools/MiaplPy/miaplpy/phase_linking.py", line 18, in <module>
    from miaplpy.lib import invert as iv
  File "invert.pyx", line 13, in init invert
ModuleNotFoundError: No module named 'isceobj'
Traceback (most recent call last):
  File "/home/insar/tools/MiaplPy/miaplpy/phase_linking.py", line 18, in <module>
    from miaplpy.lib import invert as iv
  File "invert.pyx", line 13, in init invert
ModuleNotFoundError: No module named 'isceobj'
Traceback (most recent call last):
  File "/home/insar/tools/MiaplPy/miaplpy/phase_linking.py", line 18, in <module>
    from miaplpy.lib import invert as iv
  File "invert.pyx", line 13, in init invert
ModuleNotFoundError: No module named 'isceobj'

I believe that I set the correct environment path to all ISCE, MintPy, and MiapIPy packages (as you can see in the attachment) since I can run the stackSentinel.py correctly. Could you please kindly let me know which version of ISCE is compatible with your package?

[bashrc.txt](https://github.com/insarlab/MiaplPy/files/11578848/bashrc.txt)

Sincerely,
Sayyed

**Comment by mirzaees** [comment]
Hi @SMJMirza 
easiest way is to add ISCE components to your python path:
`export PYTHONPATH=${PYTHONPATH}:${ISCE_HOME}:${ISCE_HOME}/components`

or you could also modify your `invert.pyx` script in https://github.com/insarlab/MiaplPy/blob/main/miaplpy/lib/invert.pyx#L13
add` import isce ` before line 13 and compile again with `python setup.py` command in the same directory

it should work then, let me know if you still get the same error

**Comment by SMJMirza** [comment]
Hi @mirzaees 

Thank you for your suggested solutions. Now, It works very well.

**Comment by SMJMirza** [comment]
Hi @mirzaees 

Thank you for sharing your solutions. Now, it works very well.
