### ISSUE TITLE
What is the difference between MiaplPy and Fringe ？

### ISSUE THREAD

**Issue by ZGHHGZ** [insarlab/MiaplPy#53]
What is the difference between MiaplPy and Fringe ？

**Comment by mirzaees** [comment]
Hi @ZGHHGZ, they are almost similar, just different implementations. In Fringe you have EVD with sequential mode. In Miaplpy you have EVD, EMI, PTA and sequential mode. Miaplpy has more options like different SHP tests, it has the [mintpy](https://github.com/insarlab/MintPy) structure and parallel processing capabilities.

**Comment by ZGHHGZ** [comment]
> Hi @ZGHHGZ, they are almost similar, just different implementations. In Fringe you have EVD with sequential mode. In Miaplpy you have EVD, EMI, PTA and sequential mode. Miaplpy has more options like different SHP tests, it has the [mintpy](https://github.com/insarlab/MintPy) structure and parallel processing capabilities.

What is the difference between MiaplPy and [dolphin](https://github.com/opera-adt/dolphin)?

**Comment by mirzaees** [comment]
@ZGHHGZ dolphin is designed for OPERA project purposes, although it also has some functionalities and can be used for phase linking
