### ISSUE TITLE
Is it possible to use old version of ISCE output

### ISSUE THREAD

**Issue by mohseniaref** [insarlab/MiaplPy#54]
Hi,

I was wondering if it is possible to use the old version of ISCE2 which for instance they used master instead of reference folder?
Which kind of modification might needed if we want to import data from them?

Best regards,
M

**Comment by mirzaees** [comment]
Hi @mohseniaref , it should be working with manual setting the path to inputs in your template, please follow the default pattern below and set them in your template file:
https://github.com/insarlab/MiaplPy/blob/30fa971f893fa5e596efc6538822f37f86750f06/miaplpy/defaults/auto_path.py#L21-L24
