### ISSUE TITLE
phase_linking.py does not exit for fatal error `PATCH_0360 is not inverted`

### ISSUE THREAD

**Issue by falkamelung** [insarlab/MiaplPy#56]
Hi @mirzaee 
I mentioned previously  that miaplpy does not always stops when an error occurs (https://github.com/insarlab/MiaplPy/issues/37). Here an example:  `run_03_miaplpy_concatenate_patches_0` ran for many hours and created a 137GB `run_03_miaplpy_concatenate_patches_0__1.o` file containing:
```
Error: PATCH_0360 is not inverted, run previous step (phase_linking) to complete
Error: PATCH_0360 is not inverted, run previous step (phase_linking) to complete
```

If we replace in
https://github.com/insarlab/MiaplPy/blob/30fa971f893fa5e596efc6538822f37f86750f06/miaplpy/phase_linking.py#L143
`print` by `raise RuntimeError`, so that the line reads
```
raise RuntimeError('Error: PATCH_{:04.0f} is not inverted, run previous step (phase_linking) to complete'.format(index))
```
it will exit with an exception. Could you do this? My PRs don't seem to get through.

**Comment by mirzaees** [comment]
Hi @falkamelung,

The reason it does not exit with an error at this step is because it checks if a patch has not been processed for any reason and tries to process it again. If it exits with this exception, it won't reprocess and finish automatically

**Comment by falkamelung** [comment]
Hi @mirzaees , 
are you sure? This happened in the run_3 step (concatenation). It is in the `concatenate_patches` function which I'd think is only called in the concatenation step.

**Comment by mirzaees** [comment]
Hi @falkamelung 
you are right, it is fixed now
Thank you
