### ISSUE TITLE
AttributeError: module 'generate_temporal_coherence' has no attribute 'main'

### ISSUE THREAD

**Issue by hzq2311** [insarlab/MiaplPy#66]
Hello,
   When i run miaplpy by example data.  When it run in step 8 it shows an error that is  "AttributeError: module 'generate_temporal_coherence' has no attribute 'main'".  Why it happen, I saw the main method has already defined in generate_temporal_coherence.py? and How to fix it? 

--------------------------------------------------
MiaplPy version v0.2.1, date 2023-08-22
--RUN-at-2023-08-27 23:08:35.233485--
Current directory: /mnt/d/work/test/PichinchaSenDT142
Run routine processing with arg_parser.py on steps: ['invert_network']
Remaining steps: ['timeseries_correction']
Project name: PichinchaSenDT142
--------------------------------------------------
20230827:230835 * miaplpyApp.py PichinchaSenDT142.txt --dostep invert_network --dir ./miaplpy
Project name: PichinchaSenDT142
Go to work directory: /mnt/d/work/test/PichinchaSenDT142/miaplpy
copy default template file /home/hzq/miniforge3/envs/miaplpy/lib/python3.11/site-packages/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /mnt/d/work/test/PichinchaSenDT142/PichinchaSenDT142.txt
update default template based on input custom template
    mintpy.compute.cluster: auto --> local
    mintpy.compute.numWorker: auto --> 8
    mintpy.reference.lalo: auto --> -0.1786, -78.5933
    mintpy.troposphericDelay.method: auto --> no
copy PichinchaSenDT142.txt to inputs   directory for backup.
copy smallbaselineApp.cfg  to inputs   directory for backup.
copy PichinchaSenDT142.txt to pic      directory for backup.
copy smallbaselineApp.cfg  to pic      directory for backup.
read default template file: /mnt/d/work/test/PichinchaSenDT142/miaplpy/smallbaselineApp.cfg
update default template based on input custom template
No new option value found, skip updating /mnt/d/work/test/PichinchaSenDT142/miaplpy/miaplpyApp.cfg
    mintpy.load.processor: auto --> isce
copy PichinchaSenDT142.txt to inputs   directory for backup.
copy miaplpyApp.cfg to inputs   directory for backup.
read default template file: /mnt/d/work/test/PichinchaSenDT142/miaplpy/miaplpyApp.cfg
----- Number of interferograms in the selected network: 45 -----

<><><><><><><><><> step 8 - invert_network (MiaplPy) <><><><><><><><><><>
Generate /mnt/d/work/test/PichinchaSenDT142/miaplpy/network_single_reference/run_files/run_08_miaplpy_invert_network
20230827:230839 * network_inversion.py /mnt/d/work/test/PichinchaSenDT142/miaplpy/network_single_reference/inputs/ifgramStack.h5 --template /mnt/d/work/test/PichinchaSenDT142/PichinchaSenDT142.txt --temp_coh /mnt/d/work/test/PichinchaSenDT142/miaplpy/inverted/tempCoh_full --mask-thres 0.5 --norm L2 --smooth_factor 0.001 --weight-func var --work_dir /mnt/d/work/test/PichinchaSenDT142/miaplpy/network_single_reference

ifgram_inversion_L1L2.py /mnt/d/work/test/PichinchaSenDT142/miaplpy/network_single_reference/inputs/ifgramStack.h5 -t /mnt/d/work/test/PichinchaSenDT142/PichinchaSenDT142.txt --update --norm L2 --tcoh /mnt/d/work/test/PichinchaSenDT142/miaplpy/inverted/tempCoh_full --mask-threshold 0.5 --smooth_factor 0.001
use dataset "unwrapPhase" by default
--------------------------------------------------
update mode: ON
1) output files already exist: ['timeseries.h5', 'temporalCoherence.h5', 'numInvIfgram.h5'].
2) output dataset is newer than input dataset: unwrapPhase.
3) all key configuration parameters are the same: ['obsDatasetName', 'numIfgram', 'weightFunc', 'maskDataset', 'maskThreshold', 'minRedundancy', 'minNormVelocity'].
run or skip: skip.

generate_temporal_coherence.py -d /mnt/d/work/test/PichinchaSenDT142/miaplpy/network_single_reference
Traceback (most recent call last):
  File "/home/hzq/miniforge3/envs/miaplpy/bin/network_inversion.py", line 33, in <module>
    sys.exit(load_entry_point('miaplpy==0.2.1', 'console_scripts', 'network_inversion.py')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzq/miniforge3/envs/miaplpy/lib/python3.11/site-packages/miaplpy/network_inversion.py", line 67, in main
    generate_temporal_coherence.main(iargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'generate_temporal_coherence' has no attribute 'main'
Go back to directory: /mnt/d/work/test/PichinchaSenDT142/miaplpy

###############################################################
Normal end of Non-Linear time series processing workflow!
##############################################################
Go back to directory: /mnt/d/work/test/PichinchaSenDT142/miaplpy

################################################
   Normal end of miaplpyApp processing!
################################################
Time used: 00 mins 4.7 secs

**Comment by mirzaees** [comment]
Hi @hzq2311 
There was an update after the release, have you possibly got the latest?
because I can not reproduce the error you mentioned

**Comment by hzq2311** [comment]
Hi, 
  Thank you for your reply. I reinstall the miaplpy by python -m pip install -e .("editable" mode) Then it work. I am not sure may be it is a environment config problem.

**Comment by mirzaees** [comment]
hi @hzq2311 , I am glad it works
