### ISSUE TITLE
Is it phase unwrapping without a mask？

### ISSUE THREAD

**Issue by ZGHHGZ** [insarlab/MiaplPy#67]
Hello，Is it phase unwrapping without a mask？What is the difference between this and the unwinding method of stamps?

**Comment by mirzaees** [comment]
I don't know about stamps but you can introduce a mask here, I suggest create the mask preferably in .h5 format and set the path in your template and run from `generate_ifgram` step:
https://github.com/insarlab/MiaplPy/blob/a791b131e9c6914b5148b685c0d0e97a897c3670/src/miaplpy/defaults/miaplpyApp.cfg#L87

or just run the following command before unwrapping:
`generate_unwrap_mask.py --geometry ./inputs/geometryRadar.h5 -m your_mask.h5`

**Comment by ZGHHGZ** [comment]
> 我不知道邮票，但你可以在这里介绍一个掩码，我建议最好以 .h5 格式创建掩码，并在模板中设置路径并从步骤运行：`generate_ifgram`
> 
> https://github.com/insarlab/MiaplPy/blob/a791b131e9c6914b5148b685c0d0e97a897c3670/src/miaplpy/defaults/miaplpyApp.cfg#L87
> 
> 或者只需在解开包装之前运行以下命令： `generate_unwrap_mask.py --geometry ./inputs/geometryRadar.h5 -m your_mask.h5`

The meaning is that the software's default setting is to perform unwrapping on the entire study area, rather than just on the PS and DS points. I'm not sure if my description is accurate.

**Comment by mirzaees** [comment]
@ZGHHGZ yes that's true

**Comment by ZGHHGZ** [comment]
> @ZGHHGZ yes that's true

Thank you very much for your reply.
I found the mask file for point PS in the process file, but I couldn't find the mask file for point DS.
Also, if I only perform phase unwrapping on points PS and DS, would the effect be better compared to unwrapping the entire image?

**Comment by mirzaees** [comment]
@ZGHHGZ 
DS pixels are selected based on the temporal coherence, the temporalCoherence.h5 (or inverted/tempCoh_avg and inverted/tempCoh_full) is a quality metric between 0 and 1 for DS pixels and they can be masked. The current default threshold in the app is 0.5, so if you use maskTempCoh.h5 you are basically looking at PS(coh=1)+DS(0.5<coh<1). you can change the threshold and use `generate_mask.py` to create a new mask

Currently, miaplpy is using snaphu for unwrapping and it does not support sparse network, but you can use other unwrappers if you wish.

**Comment by ZGHHGZ** [comment]
I roughly understand. Thank you for your reply.
