### ISSUE TITLE
unwrap_ifgram step errro with snaphu (NaN or infinity found in input float data)

### ISSUE THREAD

**Issue by gjustin40** [insarlab/MiaplPy#69]
I tried to run `unwrap_ifgram` step with `miaplpyApp factory.txt --dir factory2 --dostep unwrap_ifgram` 
The result like:
```
20231003:183621 * unwrap_ifgram.py --ifg /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200209/filt_fine.int --coherence /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/tempCoh_average --unwrapped_ifg /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200209/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 2834 --width 21579 --height 697946.3676910399 --num_tiles 6 --earth_radius 6339244.253900407 --wavelength 0.05546576 -m /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/mask_unwrap
snaphu -f /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200221/config_all -d /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200221/filt_fine.int 21579 -o /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200221/filt_fine.unw --tile 2 3 500 500 --nproc 6
snaphu -f /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200328/config_all -d /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200328/filt_fine.int 21579 -o /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200328/filt_fine.unw --tile 2 3 500 500 --nproc 6
20231003:183621 * unwrap_ifgram.py --ifg /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200421/filt_fine.int --coherence /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/tempCoh_average --unwrapped_ifg /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200421/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 2834 --width 21579 --height 697946.3676910399 --num_tiles 6 --earth_radius 6339244.253900407 --wavelength 0.05546576 -m /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/mask_unwrap
snaphu -f /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200209/config_all -d /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200209/filt_fine.int 21579 -o /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200209/filt_fine.unw --tile 2 3 500 500 --nproc 6
20231003:183621 * unwrap_ifgram.py --ifg /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200304/filt_fine.int --coherence /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/tempCoh_average --unwrapped_ifg /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200304/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 2834 --width 21579 --height 697946.3676910399 --num_tiles 6 --earth_radius 6339244.253900407 --wavelength 0.05546576 -m /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/mask_unwrap
snaphu -f /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200421/config_all -d /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200421/filt_fine.int 21579 -o /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200421/filt_fine.unw --tile 2 3 500 500 --nproc 6
snaphu -f /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200304/config_all -d /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200304/filt_fine.int 21579 -o /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200304/filt_fine.unw --tile 2 3 500 500 --nproc 6
Terminated
```

the log from `inverted/interferograms_single_reference/20200702_20200104/snaphu_tiles_334061` is like
```
snaphu (pid 334077): unwrapping tile at row 0, column 0

Current working directory is /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2
Reading wrapped phase from file /home/github/isce2/project/synspective_factory_area/ascending/miaplpy/factory2/inverted/interferograms_single_reference/20200702_20200104/filt_fine.int
NaN or infinity found in input float data
Abort
```

### how to fix `NaN or infinity found in input float data` error?
Thanks

the command of `ISCE2` was:
```
stackSentinel.py -s SLC/ -d DEM/*.dem.wgs84 -a AuxDir/ -o Orbits/ -b 11.0295 11.1651 106.5815 106.7192 -c 2
```

the `miaplpy` .txt file is like:
```
miaplpy.load.processor      = isce  #[isce,snap,gamma,roipac], auto for isceTops
miaplpy.load.updateMode     = auto  #[yes / no], auto for yes, skip re-loading if HDF5 files are complete
miaplpy.load.compression    = auto  #[gzip / lzf / no], auto for no.
miaplpy.load.autoPath       = no # [yes, no] auto for no
##---------Coregistered SLC images:        
miaplpy.load.slcFile        = /home/github/isce2/project/synspective_factory_area/ascending/merged/SLC/*/*.slc.full  #[path2slc_file]
##---------for ISCE only:
# miaplpy.load.metaFile       = /home/github/isce2/project/synspective_factory_area/ascending/reference/IW*.xml
miaplpy.load.metaFile       = /home/github/isce2/project/synspective_factory_area/ascending/reference/IW*.xml
# miaplpy.load.baselineDir    = /home/github/isce2/project/synspective_factory_area/ascending/baselines
miaplpy.load.baselineDir    = /home/github/isce2/project/synspective_factory_area/ascending/baselines
##---------geometry datasets:
miaplpy.load.demFile          = /home/github/isce2/project/synspective_factory_area/ascending/merged/geom_reference/hgt.rdr.full
miaplpy.load.lookupYFile      = /home/github/isce2/project/synspective_factory_area/ascending/merged/geom_reference/lat.rdr.full
miaplpy.load.lookupXFile      = /home/github/isce2/project/synspective_factory_area/ascending/merged/geom_reference/lon.rdr.full
miaplpy.load.incAngleFile     = /home/github/isce2/project/synspective_factory_area/ascending/merged/geom_reference/los.rdr.full
miaplpy.load.azAngleFile      = /home/github/isce2/project/synspective_factory_area/ascending/merged/geom_reference/los.rdr.full
miaplpy.load.shadowMaskFile   = /home/github/isce2/project/synspective_factory_area/ascending/merged/geom_reference/shadowMask.rdr.full
miaplpy.load.waterMaskFile    = None
##---------interferogram datasets:
miaplpy.load.unwFile        = ./inverted/interferograms_single_reference/*/*fine*.unw
miaplpy.load.corFile        = ./inverted/interferograms_single_reference/*/*fine*.cor
miaplpy.load.connCompFile   = ./inverted/interferograms_single_reference/*/*.unw.conncomp

##---------subset (optional):
## if both yx and lalo are specified, use lalo option unless a) no lookup file AND b) dataset is in radar coord
# miaplpy.subset.lalo         = -0.199:-0.142,-78.612:-78.578

# MiaplPy options
miaplpy.compute.numCores   = 8
miaplpy.interferograms.type = single_reference

## Mintpy options
mintpy.compute.cluster     = local  # if dask is not available, set this option to no
mintpy.compute.numWorker   = 8
mintpy.geocode.fillValue   = 0
```

**Comment by mirzaees** [comment]
@gjustin40  your interferograms seem to have NaN values. you may modify them and replace Nan values with something or you may use a mask. If all of your interferograms have nan values at the same pixels, try making a mask with `.h5` format and then use `generate_unwrap_mask.py` to update the unwrap mask before running unwrap step. The other way is to directly update unwrap mask in your inverted folder with opening and modifying it in python.

**Comment by Jesse-kearse** [comment]
I am also trying to solve this issue, and I get the same snaphu error when trying to unwrap, as it appear the interferograms are corrupted somehow. In my workflow, something has gone wrong during the phase_linking or stage. If I view the temporal coherence of "phase_series.h5" I get a blank image with uniform temporal coherence across the scene. 

view.py inverted/phase_series.h5 temporalCoherence

![Screen Shot 2023-10-05 at 2 32 16 PM](https://github.com/insarlab/MiaplPy/assets/68084910/970af14b-d434-4c19-b950-7bb521fb7d60)

The next stage of forming interferograms still worked, however the ifgs are also not displaying and appear to be "empty"

view.py inverted/interferograms_single_reference/20200205_20180615/filt_fine.int phase

![Screen Shot 2023-10-05 at 2 34 59 PM](https://github.com/insarlab/MiaplPy/assets/68084910/7762d0f3-89c2-496a-93ba-9e70ef8bc74c)

So it at least for me, its not a problem with snaphu , its something upstream. @gjustin40 if you havnt already , you could check that your unwrapped ifgs are formed correctly? 

@mirzaees  do you have any ideas what might have happened here? 

Thanks for any help

**Comment by Jesse-kearse** [comment]
Sorry, @gjustin40 , typo: check that your "wrapped" ifgs are formed correctly

**Comment by Jesse-kearse** [comment]
After doing some more digging, my issue goes all the way back to the initial slcStack.h5 file. 

view.py inputs/slcStack.h5 

![Screen Shot 2023-10-05 at 3 14 16 PM](https://github.com/insarlab/MiaplPy/assets/68084910/fff28b07-2f99-4b68-9b3b-297ca73b66b7)

Only the reference appears. The size of the .h5 file is about the size I would expect from a ROI of this size (~2.5 GB). 

Interesting that I could make it all the way through to ifg unwrapping with snaphu before noticing an issue.

I will restart from the beginning and pay closer attention to the loading of the SLC files in the load_data stage.

**Comment by Jesse-kearse** [comment]
Ok, so a long story, but I found it in the end. It turns out that I had no actual raw SLC data, the /coreg_secondarys/ directory was empty, so the .slc.full.vrt files were pointing to raw data that does not exist. 

When loading the datasets, I got the following error:

ERROR 4: ../merged/SLC/20180603/../../../coreg_secondarys/20180603/IW2/burst_01.slc.vrt: No such file or directory

Probably quite a unique problem (sorry for taking up all this space on this thread), but worth noting that Miaplpy can proceed from load_data to unwrapping before this causes a fatal error.

**Comment by gjustin40** [comment]
Thank you for your help @mirzaees @Jesse-kearse 

After reviewing the information provided above, I realized there may have been an issue in the previous step, so I decided to give it another try. In fact, it seems that the problem started when I was creating the stack in `isce2`, so I expanded the bbox range and tried again, and fortunately, it worked without any issues!

In my case, it seems that there was an issue in `run_04_miaplpy_generate_ifgram`. It appeared that the problem arose from setting a bbox that was too small during the stack creation process in isce2. I increased the size of the bbox and tried again, and it worked correctly!

I'm not sure whether the cause was the size of the bbox or the difference between the `-w` and `-c` options in `isce` when generating the stack, but the important thing is that it's working well now!

Thank you for your advice.

By the way, Can i convert Miaplpy result which is Grid format to point format like StaMPS? @mirzaees

**Comment by Jesse-kearse** [comment]
I think ISCE2 works best when you are processing at least 2 adjacent bursts, I think that is a common issue that is easily solved with increasing the bbox size to include 2 bursts.

**Comment by gjustin40** [comment]
@Jesse-kearse Thanks for your advices
I think so too.

My mistake was that I made too small subset during  `interferogram stack` step in isce2.
Subset should be applied after make stack of interferogram with more wide bbox range to prevent error.

@Jesse-kearse Do you know how to get result of Miaplpy by point like StaMPS?
In tutorial, there is a step to view PS mask in Visualization. I want to get PS with point not the grid(raster) like StaMPS

**Comment by Jesse-kearse** [comment]
Hi @gjustin40 

Is your question about displaying the data as points instead of a raster image? As I understand, StaMPS has its outputs structured as column arrays e.g. lon,lat,phs. You would need to simply get the lon,lat coordinates of each cell in Miaplpy geocoded raster, as well as the velocity value and make your own file with a lon,lat,velocity structure (e.g. a 3-column matrix). Then you could plot it with stamps, or gmt plot function, or with which ever mapping package you choose.

**Comment by gjustin40** [comment]
I asked if there is a function to convert PS masks to point format (.shp, .geojson) in Miaplpy!
I guess I can make it myself if not. 

Thank you.
