### ISSUE TITLE
unwrap_ifgram.py generates a different filename

### ISSUE THREAD

**Issue by bjmarfito** [insarlab/MiaplPy#7]
unwrap_ifgram.py generates a different filename when unwrapping is tiled. It generates the filename snaphu_tileinit_270422_filt_fine.unw instead of just filt_fine.unw. I checked the code and I suspect that the naming issue is caused by snaphu. Please see the screenshot below of my directory for your reference.
<img width="1505" alt="unwrap_ifgram_problem" src="https://user-images.githubusercontent.com/21336508/173313846-11b282ba-c4cf-4696-8529-df8c04488b9a.png">

**Comment by mirzaees** [comment]
@bjmarfito This means that SNAPHU has not finished unwrapping yet, it is merging tiles
If it is takeing longer than 2 hours, check your interferogram (filt_fine.int), it might be too big or totally decorrelated and very difficult (sometimes impossible) to unwrap. you may change your unwrapping network and choose more coherent interferograms.
After SNAPGU is done with unwrapping, the names of the files will be corrected as filt_fine.unw

**Comment by bjmarfito** [comment]
@mirzaees, thank you for providing solutions on the issue I am facing. The unwrapping step was finished but the filename is still the same. For now, I follow your suggestion to change the unwrapping network from sequential to single reference.   

I will update you once the processing is finished.

**Comment by mirzaees** [comment]
@bjmarfito, I still think that your SNAPHU did not finish
do you use jobs? maybe they run out of time
Just a quick note, do not use very long temporal or perpendicular baselines, they are usually decorrelated. 
I do not suggest single reference for your case, I would go with delaunay and check the coherence of my interferograms

**Comment by bjmarfito** [comment]
@mirzaees, I used jobs though I set the wall time for 10 days. The unwrapping finished incompletely even though the code prints out that it finished the unwrapping at a time period.

Below is the the log from the unwrapping procedure in MiaplPy.

0220614:095600 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20090829/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20090829/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20090829/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20090829/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20090829/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'81 incremental costs clipped to avoid overflow (0.000%)\n66 incremental costs clipped to avoid overflow (0.000%)\n67 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 36.26647717158 m
20220614:103216 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091014/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091014/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091014/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091014/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091014/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'84 incremental costs clipped to avoid overflow (0.000%)\n69 incremental costs clipped to avoid overflow (0.000%)\n70 incremental costs clipped to avoid overflow (0.000%)\n70 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 30.992043205102284 m
20220614:110317 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091129/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091129/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091129/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091129/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20091129/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'78 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 26.71663243373235 m
20220614:113001 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100114/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100114/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100114/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100114/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100114/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'75 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 32.1569121003151 m
20220614:120211 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100301/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100301/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100301/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100301/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100301/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'80 incremental costs clipped to avoid overflow (0.001%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 27.87204274336497 m
20220614:123004 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100901/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100901/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100901/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100901/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20100901/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'74 incremental costs clipped to avoid overflow (0.001%)\n66 incremental costs clipped to avoid overflow (0.001%)\n66 incremental costs clipped to avoid overflow (0.001%)\n66 incremental costs clipped to avoid overflow (0.001%)\none or more interferogram dimensions too large\n'
Time spent: 26.314400704701743 m
20220614:125624 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101017/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101017/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101017/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101017/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101017/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'78 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 32.33874227205912 m
20220614:132845 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101202/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101202/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101202/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101202/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20101202/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'80 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 30.32989749511083 m
20220614:135905 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110117/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110117/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110117/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110117/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110117/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'78 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 27.874361062049864 m
20220614:142658 * unwrap_ifgram.py --ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110304/filt_fine.int --coherence /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/tempCoh_average --unwrapped_ifg /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110304/filt_fine.unw --max_discontinuity 1.2 --init_method MCF --length 36864 --width 4762 --height 698539.3483002761 --num_tiles 17 --earth_radius 6337499.640502797 --wavelength 0.2360571 -m /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/mask_unwrap
snaphu -f /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110304/config_all -d /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110304/filt_fine.int 4762 -o /home/data/INSAR_processing/bjm_ts/kalimantan/miaplpy/inverted/interferograms_single_reference/20100717_20110304/filt_fine.unw --tile 4 4 500 500 --nproc 17
b'78 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\n68 incremental costs clipped to avoid overflow (0.000%)\none or more interferogram dimensions too large\n'
Time spent: 31.716273935635886 m

**Comment by mirzaees** [comment]
@bjmarfito 
This is huge (length 36864 width 4762)!
The message in your log says that it didn't finish because it is too large
`none or more interferogram dimensions too large`
The unwrapping in full resolution is a real problem, we usually suggest processing a small region instead of the whole scene. The largest dimension I have processed so far is 12000*6000 and it was not easy

**Comment by bjmarfito** [comment]
@mirzaees, I see. Thank you for giving an explanation for the issue I am encountering during unwrapping. Yeah, I would consider your suggestion of using a smaller region for data processing.

**Comment by bjmarfito** [comment]
My unwrapping issue is finally solved by using a smaller region. Thank you for the suggestion @mirzaees!
