### ISSUE TITLE
How to get full resolution result?

### ISSUE THREAD

**Issue by gjustin40** [insarlab/MiaplPy#70]
I used the config text file "PichinchaSenDT142.txt" as provided in the example and did not modify any options before running it.

I followed the steps outlined in [juyter notebook](https://nbviewer.org/github/insarlab/MiaplPy_notebooks/blob/main/miaplpyApp.ipynb) exactly as described. 
I also executed the "3. Correct for geolocation step" at the bottom of the notebook.

I know that the resolution of Sentinel-1 is `5 x 20 m`, but the result of above steps is like:
![image](https://github.com/insarlab/MiaplPy/assets/25999141/66ea7a6a-3f56-4ced-8763-79dbd5353265)

Above image is from QGIS `Measure` function

1. Are there any options to get the full resolution(5x20m)?
2. Why is it not a square but a rectangle in shape?
3. Can it be converted into a square?

**Comment by mirzaees** [comment]
Hi @gjustin40 
you are probably looking at the geocoded products, the range/doppler coordinates are in full resolution but for geocoded, you need to modify lalo step in mintpy options for geocoding:

https://github.com/insarlab/MintPy/blob/cd1cae93922612856820c422bb7e179c40fda2d5/src/mintpy/defaults/smallbaselineApp.cfg#L321

The default is coarser than full res. Also you don't need geolocation correction if you are not looking at precise location of structures. If you are interested in that, make sure your demError is correct otherwise you get false results.

**Comment by gjustin40** [comment]
Thanks for your advice. @mirzaees

Than How to set the value of `mintpy.geocode.laloStep` to get full resolution in geocoding?
Furthermore, Could you answer my other questions, please?

2. Why is it not a square but a rectangle in shape?
3. Can it be converted into a square?

**Comment by mirzaees** [comment]
@gjustin40 
Your questions are all related to lalo step. you need to specify the final grid resolution in x and y direction. the default has different strategy to set it based on metadata but you can manually set it to be square with a defined resolution. In your template file add the option I mentioned before. you can check all the other options of mintpy for geocoding here:

https://github.com/insarlab/MintPy/blob/cd1cae93922612856820c422bb7e179c40fda2d5/src/mintpy/defaults/smallbaselineApp.cfg#L314-L323

**Comment by gjustin40** [comment]
Thanks, @mirzaees 

I changed the value of `mintpy.geocode.laloStep` from `auto[-0.000555556,0.000555556]` to `10m[,0.000092593,0.000092593]`.
After run `smallbaselineApp.py factory.txt --dir ./miaplpy --start geocode` by above config, 
the output of `save_gdal.py geo_velocity.h5` is same as before on QGIS.

I want to generate `tif` data that has highest resolution which Sentinel-1 has (5x20m).
But it seems that `mintpy.geocode.laloStep` option applied just on geo_velocity.png which used 'view.py' command, not `save_gdal.py`

What should i do to get full resolution of `tif` data of `geo_velocity.h5`?

**Comment by mirzaees** [comment]
@gjustin40 
As far as I know, that option should fix it. 
But generally your question is for mintpy, please make an issue on that repo and hopefully Yunjun can help you better with geocoding.

**Comment by gjustin40** [comment]
Thanks for your hlep. @mirzaees 

I will get the information from MintPy.
