### ISSUE TITLE
Assistance Required with MiaplPy InSAR Data Processing Issue

### ISSUE THREAD

**Issue by Arcyzr** [insarlab/MiaplPy#73]
Dear Developer,

I am a novice in processing InSAR data using "MiaplPy." After successfully installing the software and running the test command "miaplpyApp.py -h," I proceeded to import data for processing. However, I encountered an error during the second step, which is as follows:
><><><><><><><><> step 2 - phase_linking (MiaplPy) <><><><><><><><><><>
Generate /media/yzr/BHTD/1212test_slc/miaplpy/network_single_reference/run_files/run_02_miaplpy_phase_linking
Total number of PATCHES: 3024
Number of tasks for step phase inversion: 756
Traceback (most recent call last):
  File "/home/yzr/tools/MiaplPy/miaplpy/phase_linking.py", line 17, in <module>
    from miaplpy.lib import utils as iut
ImportError: cannot import name 'utils' from 'miaplpy.lib' (unknown location)
...
I have attempted to add the path "MiaplPy/src/miaplpy/lib/" to the system environment, but the same error persists. Could you please advise on how to resolve this issue?

Thank you for your assistance.

Kind regards,

yzr

**Comment by mirzaees** [comment]
Hi @Arcyzr 
you have not compiled the code properly, please follow [installation](https://github.com/insarlab/MiaplPy/blob/main/docs/installation.md)

**Comment by Arcyzr** [comment]
> Hi @Arcyzr you have not compiled the code properly, please follow [installation](https://github.com/insarlab/MiaplPy/blob/main/docs/installation.md)
Thank you for your response. I have reinstalled the software following the 'installation' guide, and compiled it using 'python setup.py build_ext –inplace' and 'python setup.py install'. Now, 'MiaplPy' is functioning properly.

**Comment by Arcyzr** [comment]
@mirzaees 
Thank you for your response. I have reinstalled the software following the 'installation' guide, and compiled it using 'python setup.py build_ext –inplace' and 'python setup.py install'. Now, 'MiaplPy' is functioning properly.

**Comment by gungputra03** [comment]
I have performed a **coregistered stack** using ISCE, which I intend to process further using MiaplPy. However, why is the processing in MiaplPy taking an extremely long time and not producing any output in the form of PNG files? The directory generated from **dir miaplpy/network_single_reference**, named **"run_files"**, contains only two files: **run_01_miaplpy_load_data** and **run_02_miaplpy_phase_linking**, whereas there should be 9 steps to be executed. Additionally, the processing is stuck at the second step, **phase linking**, for hours without any progress.

![Image](https://github.com/user-attachments/assets/4f316807-0cce-4438-b441-d173eedaf294)

![Image](https://github.com/user-attachments/assets/cf9a9638-fb42-4751-970e-7cbdbd875489)
