### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by hzq2311** [insarlab/MiaplPy#8]
Thanks for your great work. and I want to test it.
When i finished the install of miaplpy, an type "miaplpyApp.py -h" in terminal it shows:

 from miaplpy.objects.arg_parser import MiaplPyParser
ModuleNotFoundError: No module named 'miaplpy'

Am i mssing some step?

**Comment by mirzaees** [comment]
Hi @hzq2311 
Could you please check your PATH and PYTHONPATH to be properly set based on step 1:
https://github.com/insarlab/MiaplPy/blob/main/docs/installation.md

**Comment by hzq2311** [comment]
Yes,you are right the PYTHONPATH is uncorrected set. and it work after fix it. Thanks
