### ISSUE TITLE
Difference ISCE 'slc' and 'interferogram' workflow as input

### ISSUE THREAD

**Issue by MarritL** [insarlab/MiaplPy#88]
Hi, 

I understood I can use the ISCE workflows 'interferogram' and 'slc' in stackSentinel.py to preprocess the SLC's for MiaPlPy. 

Do both stacks lead to the same results in miaPlPy? If not, which one is recommended? And on which data does the PL algorithm work if using the 'slc' workflow? From the scientific article (https://doi.org/10.1016/j.cageo.2022.105291) it seemed that a full network of interferograms is needed for the PL algorithm, is that correct?

Thanks :-)

**Comment by ZGHHGZ** [comment]
The result is the same in both ways. miaplpy only needs the aligned SLC data. If you only need miaplpy, you can set the type to 'slc'. 'interferogram' will do interferometric unwrapping, which will take more time, but you can prepare the data for SBAS-INSAR processing by mintpy this way.

**Comment by MarritL** [comment]
Great. Thanks you!
