### ISSUE TITLE
Phase linking bug

### ISSUE THREAD

**Issue by ZGHHGZ** [insarlab/MiaplPy#91]
In recent months, I through the installation guide (https://github.com/insarlab/MiaplPy/blob/main/docs/installation.md) installed MiaplPy on multiple devices, However, in the phase linking, the calculation is very slow, and under the premise of the same data volume and parameter Settings, it takes 10 times the previous time. After I reduced the version of scipy and numpy, the operation time returned to normal. Is it because the version of scipy or numpy is too high? I hope this problem can be corrected, thank you for your reply.

**Comment by jjeeffff** [comment]
Hello, I've got the same problem. Could you please tell me the version of scipy and numpy that you are using?

**Comment by ZGHHGZ** [comment]
>>> print(numpy.version.version)
1.26.4
>>> print(scipy.version.version)
1.12.0

**Comment by jjeeffff** [comment]
> > > > print(numpy.version.version)
> > > > 1.26.4
> > > > print(scipy.version.version)
> > > > 1.12.0

Thanks for replying.

**Comment by mirzaees** [comment]
Hi @ZGHHGZ and @jjeeffff 
It might be the version but I did not have time to update it, I welcome any contributions though

**Comment by Jesse-kearse** [comment]
@ZGHHGZ @jjeeffff  Did you find a version of SciPy / Numpy that is stable with the phase_linking step?

**Comment by ZGHHGZ** [comment]
> 您是否找到与 phase_linking 步骤稳定的 SciPy / Numpy 版本？



> > > > print(numpy.version.version)
> > > > 1.26.4
> > > > print(scipy.version.version)
> > > > 1.12.0

**Comment by Jesse-kearse** [comment]
Thank you for replying @ZGHHGZ . 

Sorry, I am confused - you are not experiencing any issues with these versions ? I thought these were the versions that might be causing the slow phase-linking problem as in your original comment?

I have downgraded to 
numpy=1.23.1
scipy=1.10.1 

and I am still experiencing the slow phase-linking.

thanks for any further help you can provide
