### ISSUE TITLE
update stack with new data

### ISSUE THREAD

**Issue by MarritL** [insarlab/MiaplPy#94]
Hi, 

We processed a SLC stack with miaplpy and obtained our displacement result. 
After having updated the SLC stack with two months of new data with ISCE. We would like to update also the displacement results. 
Is this possible without reprocessing the entire stack?

Thank you for any suggestions!

**Comment by mirzaees** [comment]
Hi @MarritL, it's an open science question and not so straightforward to update,  we don't have an implementation in miaplpy for that yet.

**Comment by MarritL** [comment]
Ok, thank you. :-)
